### ISSUE TITLE
Insert a README.md

### ISSUE THREAD

**Issue by brunoocasali** [prosi-org/pinfluence#1]
Hello World!

- [x] Add a readme file to project
  - [x] Add description about project
  - [x] Badges?
  - [x] How to contribute
  - [x] Code of Conduct
  - [x] Add a how to build the project (pre-requisites)

**Comment by rafaels88** [comment]
Thanks, Bruno! I totally forgot that...

**Comment by rafaels88** [comment]
We are not going to have a badge right now.
